/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Avatar;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Details about system and custom avatars.
 */
@Schema(description = "Details about system and custom avatars.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-21T14:14:33.600-07:00[America/Los_Angeles]")

public class Avatars {
  @SerializedName("custom")
  private List<Avatar> custom = null;

  @SerializedName("system")
  private List<Avatar> system = null;

   /**
   * Custom avatars list.
   * @return custom
  **/
  @Schema(description = "Custom avatars list.")
  public List<Avatar> getCustom() {
    return custom;
  }

   /**
   * System avatars list.
   * @return system
  **/
  @Schema(description = "System avatars list.")
  public List<Avatar> getSystem() {
    return system;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Avatars avatars = (Avatars) o;
    return Objects.equals(this.custom, avatars.custom) &&
        Objects.equals(this.system, avatars.system);
  }

  @Override
  public int hashCode() {
    return Objects.hash(custom, system);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Avatars {\n");
    
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
