/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The details of a custom field context.
 */
@Schema(description = "The details of a custom field context.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-21T14:14:33.600-07:00[America/Los_Angeles]")

public class CustomFieldContext {
  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("isAnyIssueType")
  private Boolean isAnyIssueType = null;

  @SerializedName("isGlobalContext")
  private Boolean isGlobalContext = null;

  @SerializedName("name")
  private String name = null;

  public CustomFieldContext description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the context.
   * @return description
  **/
  @Schema(required = true, description = "The description of the context.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomFieldContext id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the context.
   * @return id
  **/
  @Schema(required = true, description = "The ID of the context.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomFieldContext isAnyIssueType(Boolean isAnyIssueType) {
    this.isAnyIssueType = isAnyIssueType;
    return this;
  }

   /**
   * Whether the context apply to all issue types.
   * @return isAnyIssueType
  **/
  @Schema(required = true, description = "Whether the context apply to all issue types.")
  public Boolean isIsAnyIssueType() {
    return isAnyIssueType;
  }

  public void setIsAnyIssueType(Boolean isAnyIssueType) {
    this.isAnyIssueType = isAnyIssueType;
  }

  public CustomFieldContext isGlobalContext(Boolean isGlobalContext) {
    this.isGlobalContext = isGlobalContext;
    return this;
  }

   /**
   * Whether the context is global.
   * @return isGlobalContext
  **/
  @Schema(required = true, description = "Whether the context is global.")
  public Boolean isIsGlobalContext() {
    return isGlobalContext;
  }

  public void setIsGlobalContext(Boolean isGlobalContext) {
    this.isGlobalContext = isGlobalContext;
  }

  public CustomFieldContext name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the context.
   * @return name
  **/
  @Schema(required = true, description = "The name of the context.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldContext customFieldContext = (CustomFieldContext) o;
    return Objects.equals(this.description, customFieldContext.description) &&
        Objects.equals(this.id, customFieldContext.id) &&
        Objects.equals(this.isAnyIssueType, customFieldContext.isAnyIssueType) &&
        Objects.equals(this.isGlobalContext, customFieldContext.isGlobalContext) &&
        Objects.equals(this.name, customFieldContext.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, isAnyIssueType, isGlobalContext, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldContext {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isAnyIssueType: ").append(toIndentedString(isAnyIssueType)).append("\n");
    sb.append("    isGlobalContext: ").append(toIndentedString(isGlobalContext)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
