/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details about a project role.
 */
@Schema(description = "Details about a project role.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-21T14:14:33.600-07:00[America/Los_Angeles]")

public class ProjectRoleDetails {
  @SerializedName("admin")
  private Boolean admin = null;

  @SerializedName("default")
  private Boolean _default = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("roleConfigurable")
  private Boolean roleConfigurable = null;

  @SerializedName("scope")
  private AllOfProjectRoleDetailsScope scope = null;

  @SerializedName("self")
  private String self = null;

  @SerializedName("translatedName")
  private String translatedName = null;

   /**
   * Whether this role is the admin role for the project.
   * @return admin
  **/
  @Schema(description = "Whether this role is the admin role for the project.")
  public Boolean isAdmin() {
    return admin;
  }

   /**
   * Whether this role is the default role for the project.
   * @return _default
  **/
  @Schema(description = "Whether this role is the default role for the project.")
  public Boolean isDefault() {
    return _default;
  }

   /**
   * The description of the project role.
   * @return description
  **/
  @Schema(description = "The description of the project role.")
  public String getDescription() {
    return description;
  }

   /**
   * The ID of the project role.
   * @return id
  **/
  @Schema(description = "The ID of the project role.")
  public Long getId() {
    return id;
  }

  public ProjectRoleDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the project role.
   * @return name
  **/
  @Schema(description = "The name of the project role.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * Whether the roles are configurable for this project.
   * @return roleConfigurable
  **/
  @Schema(description = "Whether the roles are configurable for this project.")
  public Boolean isRoleConfigurable() {
    return roleConfigurable;
  }

   /**
   * The scope of the role. Indicated for roles associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO).
   * @return scope
  **/
  @Schema(description = "The scope of the role. Indicated for roles associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO).")
  public AllOfProjectRoleDetailsScope getScope() {
    return scope;
  }

   /**
   * The URL the project role details.
   * @return self
  **/
  @Schema(description = "The URL the project role details.")
  public String getSelf() {
    return self;
  }

  public ProjectRoleDetails translatedName(String translatedName) {
    this.translatedName = translatedName;
    return this;
  }

   /**
   * The translated name of the project role.
   * @return translatedName
  **/
  @Schema(description = "The translated name of the project role.")
  public String getTranslatedName() {
    return translatedName;
  }

  public void setTranslatedName(String translatedName) {
    this.translatedName = translatedName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectRoleDetails projectRoleDetails = (ProjectRoleDetails) o;
    return Objects.equals(this.admin, projectRoleDetails.admin) &&
        Objects.equals(this._default, projectRoleDetails._default) &&
        Objects.equals(this.description, projectRoleDetails.description) &&
        Objects.equals(this.id, projectRoleDetails.id) &&
        Objects.equals(this.name, projectRoleDetails.name) &&
        Objects.equals(this.roleConfigurable, projectRoleDetails.roleConfigurable) &&
        Objects.equals(this.scope, projectRoleDetails.scope) &&
        Objects.equals(this.self, projectRoleDetails.self) &&
        Objects.equals(this.translatedName, projectRoleDetails.translatedName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(admin, _default, description, id, name, roleConfigurable, scope, self, translatedName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectRoleDetails {\n");
    
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    roleConfigurable: ").append(toIndentedString(roleConfigurable)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    translatedName: ").append(toIndentedString(translatedName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
