/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details about a user assigned to a project role.
 */
@Schema(description = "Details about a user assigned to a project role.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-21T14:14:33.600-07:00[America/Los_Angeles]")

public class RoleActor {
  @SerializedName("actorGroup")
  private AllOfRoleActorActorGroup actorGroup = null;

  @SerializedName("actorUser")
  private AllOfRoleActorActorUser actorUser = null;

  @SerializedName("avatarUrl")
  private String avatarUrl = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  /**
   * The type of role actor.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    @SerializedName("atlassian-group-role-actor")
    GROUP_ROLE_ACTOR("atlassian-group-role-actor"),
    @SerializedName("atlassian-user-role-actor")
    USER_ROLE_ACTOR("atlassian-user-role-actor");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

   /**
   * Get actorGroup
   * @return actorGroup
  **/
  @Schema(description = "")
  public AllOfRoleActorActorGroup getActorGroup() {
    return actorGroup;
  }

   /**
   * Get actorUser
   * @return actorUser
  **/
  @Schema(description = "")
  public AllOfRoleActorActorUser getActorUser() {
    return actorUser;
  }

   /**
   * The avatar of the role actor.
   * @return avatarUrl
  **/
  @Schema(description = "The avatar of the role actor.")
  public String getAvatarUrl() {
    return avatarUrl;
  }

   /**
   * The display name of the role actor. For users, depending on the user’s privacy setting, this may return an alternative value for the user&#x27;s name.
   * @return displayName
  **/
  @Schema(description = "The display name of the role actor. For users, depending on the user’s privacy setting, this may return an alternative value for the user's name.")
  public String getDisplayName() {
    return displayName;
  }

   /**
   * The ID of the role actor.
   * @return id
  **/
  @Schema(description = "The ID of the role actor.")
  public Long getId() {
    return id;
  }

   /**
   * This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.
   * @return name
  **/
  @Schema(description = "This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.")
  public String getName() {
    return name;
  }

   /**
   * The type of role actor.
   * @return type
  **/
  @Schema(description = "The type of role actor.")
  public TypeEnum getType() {
    return type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleActor roleActor = (RoleActor) o;
    return Objects.equals(this.actorGroup, roleActor.actorGroup) &&
        Objects.equals(this.actorUser, roleActor.actorUser) &&
        Objects.equals(this.avatarUrl, roleActor.avatarUrl) &&
        Objects.equals(this.displayName, roleActor.displayName) &&
        Objects.equals(this.id, roleActor.id) &&
        Objects.equals(this.name, roleActor.name) &&
        Objects.equals(this.type, roleActor.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actorGroup, actorUser, avatarUrl, displayName, id, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleActor {\n");
    
    sb.append("    actorGroup: ").append(toIndentedString(actorGroup)).append("\n");
    sb.append("    actorUser: ").append(toIndentedString(actorUser)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
