/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Identifiers for a UI modification.
 */
@Schema(description = "Identifiers for a UI modification.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-07-21T14:14:33.600-07:00[America/Los_Angeles]")

public class UiModificationIdentifiers {
  @SerializedName("id")
  private String id = null;

  @SerializedName("self")
  private String self = null;

   /**
   * The ID of the UI modification.
   * @return id
  **/
  @Schema(required = true, description = "The ID of the UI modification.")
  public String getId() {
    return id;
  }

   /**
   * The URL of the UI modification.
   * @return self
  **/
  @Schema(required = true, description = "The URL of the UI modification.")
  public String getSelf() {
    return self;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UiModificationIdentifiers uiModificationIdentifiers = (UiModificationIdentifiers) o;
    return Objects.equals(this.id, uiModificationIdentifiers.id) &&
        Objects.equals(this.self, uiModificationIdentifiers.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, self);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UiModificationIdentifiers {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
