/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateUiModificationDetails;
import io.swagger.client.model.PageBeanUiModificationDetails;
import io.swagger.client.model.UiModificationIdentifiers;
import io.swagger.client.model.UpdateUiModificationDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UiModificationsAppsApi
 */
@Ignore
public class UiModificationsAppsApiTest {

    private final UiModificationsAppsApi api = new UiModificationsAppsApi();

    /**
     * Create UI modification
     *
     * Creates a UI modification. UI modification can only be created by Forge apps.  Each app can define up to 100 UI modifications. Each UI modification can define up to 1000 contexts.  **[Permissions](#permissions) required:**   *  *None* if the UI modification is created without contexts.  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for one or more projects, if the UI modification is created with contexts.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUiModificationTest() throws Exception {
        CreateUiModificationDetails body = null;
        UiModificationIdentifiers response = api.createUiModification(body);

        // TODO: test validations
    }
    /**
     * Delete UI modification
     *
     * Deletes a UI modification. All the contexts that belong to the UI modification are deleted too. UI modification can only be deleted by Forge apps.  **[Permissions](#permissions) required:** None.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUiModificationTest() throws Exception {
        String uiModificationId = null;
        Object response = api.deleteUiModification(uiModificationId);

        // TODO: test validations
    }
    /**
     * Get UI modifications
     *
     * Gets UI modifications. UI modifications can only be retrieved by Forge apps.  **[Permissions](#permissions) required:** None.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUiModificationsTest() throws Exception {
        Long startAt = null;
        Integer maxResults = null;
        String expand = null;
        PageBeanUiModificationDetails response = api.getUiModifications(startAt, maxResults, expand);

        // TODO: test validations
    }
    /**
     * Update UI modification
     *
     * Updates a UI modification. UI modification can only be updated by Forge apps.  Each UI modification can define up to 1000 contexts.  **[Permissions](#permissions) required:**   *  *None* if the UI modification is created without contexts.  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for one or more projects, if the UI modification is created with contexts.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUiModificationTest() throws Exception {
        UpdateUiModificationDetails body = null;
        String uiModificationId = null;
        Object response = api.updateUiModification(body, uiModificationId);

        // TODO: test validations
    }
}
